"""empty message

Revision ID: 3dbfb87533b7
Revises: 7352c7e961a7
Create Date: 2019-07-24 10:52:01.044152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dbfb87533b7'
down_revision = '7352c7e961a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('description', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_movies_description'), 'movies', ['description'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_description'), table_name='movies')
    op.drop_column('movies', 'description')
    # ### end Alembic commands ###
